### ISSUE TITLE
How to separate host url for XMLHttpRequest ?

### ISSUE THREAD

**Issue by azamiya** [tigerscave/ada-simple-db#1]
### Problem
I have two environment,
dev(localhost), 
staging(Heroku)

For XMLHttpRequest, I want to use each environment endpoint.

Ex.
https://github.com/tigerscave/ada-simple-db/blob/master/public/createUser.js#L3
```
const endpoint = process.env.ENDPOINT;

const createUser = (name, email) => {
  const xhr = new XMLHttpRequest();
  xhr.open("POST", `${endpoint}/users`);
  xhr.onreadystatechange = () => {
    console.log(xhr)
    if(xhr.readyState === 4 && xhr.status === 201) {
      alert("user added!");

    }
  }
```

But I can not find the way to use separate endpoint on client side. (server side i'm using `dotenv`)

### Expected behavior

on localhost, I want to use localhost endpoint (like `http://localhost:5455`)
on Heroku, I want to use Heroku server endpoint (like `https://simple-db.herokuapp.com/`)

### How to solve ?

- should I use some build config ? (like `webpack` ?)

**Comment by hrl7** [comment]
if the origins are same, the easiest way is using `window.origin`.
for some security reason, you might restrict origin by whitelist.
also you can put the origin by using webpack.

FYI, you should use `fetch` instead of `XMLHttpRequest` because `fetch` is better alternative.
